name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install your package plus test/runtime deps
          pip install . 
          pip install pytest MDAnalysis

      - name: Download test data from Box
        run: |
          mkdir -p tests/data
          curl -L "https://weizmann.box.com/s/p1uohi0f9fowk33bm55p3qs7tmfbrf8d?dl=1" \
            -o tests/data/step5_input.psf
          curl -L "https://weizmann.box.com/s/uph9a74zmx7z24yh3ulafwcl8xj4kod2?dl=1" \
            -o tests/data/MD_Aligned.dcd

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: tests/data
          key: ${{ runner.os }}-poredata-v1

      - name: Cleanup & smoke‑test
        run: ./tests/run_samples.py

      - name: Run pytest
        run: pytest -q
